stages:
  - test
  - deploy

variables:
  APP_NAME: rimg

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

test:
  stage: test
  image: node:latest

  before_script:
    - npm ci --cache .npm --prefer-offline
  
  script:
   - npm test

deploy:
  image: ilyasemenov/gitlab-ci-git-push
  stage: deploy
  only:
    refs:
      - master
    changes:
      - "**/*.ts"
      - "**/*.js"
      - "**/*.json"
  script:
    - git-push ssh://dokku@$REMOTE_HOST/$APP_NAME
