name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths:
    - ".github/workflows/deploy.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: mirror-repository
        uses: ct-martin/mirror-action@master
        with:
          REMOTE: ${{ secrets.GIT_REMOTE }}
          GIT_USERNAME: dokku
          GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_KEY }}
          DEBUG: "true"
          PUSH_ALL_REFS: "false"
