name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy.yml"
      - '**.ts'
      - '**.js'
      - '**.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Git Foo # Copy main branch b/c Dokku needs a master branch (default + ps:rebuild)
        run: |-
          git branch -C origin/main origin/master
      - uses: spyoungtech/mirror-action@master
        with:
          REMOTE: ${{ secrets.GIT_REMOTE }}
          GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_KEY }}
          GIT_SSH_NO_VERIFY_HOST: "true"
#          GIT_SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
          SECRET_REMOTE_DOMAIN: ${{ secrets.SECRET_REMOTE_DOMAIN }}
          SECRET_REMOTE_IP: ${{ secrets.SECRET_REMOTE_IP }}
