name: CI

on:
  push:
    branches:
    - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: mirror-repository
        uses: spyoungtech/mirror-action@spyoungtech-patch-1
        with:
          REMOTE: ${{ secrets.GIT_REMOTE }}
          GIT_USERNAME: dokku
          GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_KEY }}
          DEBUG: "true"
          PUSH_ALL_REFS: "false"
