name: Deploy

# Note: the `with` parameters don't actually match the code logic for the Action used
# See: https://github.com/spyoungtech/mirror-action/blob/2b758bf0df34487cd933ac69f251b9d3cbbfc442/entrypoint.sh#L35-L37
# Also: "1" is used to pass [[ "1" -ne "" ]]
# The wrong comparator was used; this shouldn't have been needed

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: mirror-repository
        uses: ct-martin/mirror-action@master
        with:
          REMOTE: ${{ secrets.GIT_REMOTE }}
          GIT_USERNAME: dokku
          GIT_SSH_PRIVATE_KEY: "1"
          SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_KEY }}
          DEBUG: "true"
          PUSH_ALL_REFS: "false"
