name: Code Tests

on:
  push:
    paths:
      - '.github/workflows/test.yml'
      - '**.ts'
      - '**.js'
      - '**.json'
  pull_request:
    paths:
      - '**.ts'
      - '**.js'
      - '**.json'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
    - run: npm test
    - run: npm run build --if-present
      env:
        CI: true
